"""AgentState definition for LangGraph supervisor orchestration.

Implements Section 6.7 and Section 6.8.4 of the project specification.
"""

from __future__ import annotations

from typing import Annotated, Any, Dict, List, Literal, Optional
from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages
from typing_extensions import TypedDict


# Valid worker choices made by the supervisor
WorkerNode = Literal[
    "PolicyRAG",
    "NetworkAnalytics",
    "NetworkDiagnosticsADK",
    "BillingResolutionADK",
    "CustomerCommsCrew",
    "FINISH",
]


class TraceItem(TypedDict):
    """Execution trace item for Streamlit and audit trail."""
    worker: str
    output: str


class AgentState(TypedDict):
    """Shared state for the LangGraph multi-agent supervisor graph.

    Fields:
      - messages: conversation history (append-only across nodes)
      - next: supervisor routing decision ('PolicyRAG', 'NetworkAnalytics', etc., or 'FINISH')
      - user_query: original customer / staff question
      - agent_context: accumulated specialist findings string passed into CrewAI
      - execution_trace: ordered record of worker runs with truncated outputs
      - final_response: polished customer-ready response generated by CustomerCommsCrew
    """

    messages: Annotated[List[BaseMessage], add_messages]
    next: str
    user_query: str
    agent_context: str
    execution_trace: List[Dict[str, Any]]
    final_response: str
